name: test
on:
  push:
    branches-ignore:
      - master
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: test
        run: cargo test --verbose
            
