name: publish
on:
  push:
    branches:
      - master

jobs:
  build-and-publish:
    name: Building and publishing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build docker image
        run: docker buildx build --platform linux/arm,linux/arm64,linux/amd64/v8 . -t hilmm
      - name: push to github packages 
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          repository: sonac/hilmm/hilmm
          tag_with_ref: true

